# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_test2(self):
    # Test name: test2
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.flipkart.com/")
    # 2 | setWindowSize | 1440x900 | 
    self.driver.set_window_size(1440, 900)
    # 3 | mouseOver | css=.\_1mIbUg:nth-child(2) .kJjFO0 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1mIbUg:nth-child(2) .kJjFO0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | name=q | 
    self.driver.find_element(By.NAME, "q").click()
    # 5 | click | css=.\_1HeMA2 | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1HeMA2").click()
    # 6 | mouseOver | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(2) .\_396cs4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(2) .\\_396cs4")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(2) .\_396cs4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | mouseOver | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(1) .\_396cs4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(1) .\\_396cs4")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | click | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(1) .\_396cs4 | 
    self.vars["window_handles"] = self.driver.window_handles
    # 10 | storeWindowHandle | root | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(1) .\\_396cs4").click()
    # 11 | selectWindow | handle=${win1803} | 
    self.vars["win1803"] = self.wait_for_window(2000)
    # 12 | selectWindow | handle=${root} | 
    self.vars["root"] = self.driver.current_window_handle
    # 13 | runScript | window.scrollTo(0,134) | 
    self.driver.switch_to.window(self.vars["win1803"])
    # 14 | mouseOver | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(1) .\_2rpwqI > div:nth-child(1) > div | 
    self.driver.switch_to.window(self.vars["root"])
    # 15 | mouseOut | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(1) .\_2rpwqI > div:nth-child(1) > div | 
    self.driver.execute_script("window.scrollTo(0,134)")
    # 16 | mouseOver | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(1) .\_396cs4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(1) .\\_2rpwqI > div:nth-child(1) > div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | click | css=.\_1AtVbE:nth-child(2) > .\_13oc-S > div:nth-child(1) .\_396cs4 | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 18 | selectWindow | handle=${win9516} | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(1) .\\_396cs4")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 19 | selectWindow | handle=${root} | 
    self.vars["window_handles"] = self.driver.window_handles
    # 20 | mouseOver | linkText=Trimmers | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) > .\\_13oc-S > div:nth-child(1) .\\_396cs4").click()
    # 21 | mouseOut | linkText=Trimmers | 
    self.vars["win9516"] = self.wait_for_window(2000)
    # 22 | selectWindow | handle=${win1803} | 
    self.driver.switch_to.window(self.vars["win9516"])
    # 23 | runScript | window.scrollTo(0,2903) | 
    self.driver.switch_to.window(self.vars["root"])
    # 24 | runScript | window.scrollTo(0,2693) | 
    element = self.driver.find_element(By.LINK_TEXT, "Trimmers")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 25 | click | css=.\_1t_O3S | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 26 | runScript | window.scrollTo(0,0) | 
    self.driver.switch_to.window(self.vars["win1803"])
    # 27 | click | css=.\_1AtVbE:nth-child(3) .\_3dsJAO:nth-child(2) | 
    self.driver.execute_script("window.scrollTo(0,2903)")
    # 28 | click | css=.FhkMJZ | 
    self.driver.execute_script("window.scrollTo(0,2693)")
    # 29 | runScript | window.scrollTo(0,0) | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1t_O3S").click()
    # 30 | click | css=.\_1AtVbE:nth-child(2) .\_3dsJAO:nth-child(2) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 31 | click | css=.FhkMJZ | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(3) .\\_3dsJAO:nth-child(2)").click()
    # 32 | runScript | window.scrollTo(0,78) | 
    self.driver.find_element(By.CSS_SELECTOR, ".FhkMJZ").click()
    # 33 | runScript | window.scrollTo(0,1816) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 34 | close |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) .\\_3dsJAO:nth-child(2)").click()
    # 35 | selectWindow | handle=${win9516} | 
    self.driver.find_element(By.CSS_SELECTOR, ".FhkMJZ").click()
    # 36 | click | css=.\_2xm1JU | 
    self.driver.execute_script("window.scrollTo(0,78)")
    self.driver.execute_script("window.scrollTo(0,1816)")
    self.driver.close()
    self.driver.switch_to.window(self.vars["win9516"])
    self.driver.find_element(By.CSS_SELECTOR, ".\\_2xm1JU").click()
  
